#!/bin/bash

sudo npm install -g xmlbuilder
sudo npm install -g archiver
sudo npm install -g wordwrap
sudo npm install -g winston
sudo npm install -g ios-sim
sudo npm install -g utile
sudo npm install -g read
sudo npm install -g revalidator
sudo npm install -g cycle
sudo npm install -g stack-trace
sudo npm install -g pkginfo
sudo npm install -g through
sudo npm install -g from
sudo npm install -g duplexer
sudo npm install -g map-stream
sudo npm install -g pause-stream
sudo npm install -g split
sudo npm install -g stream-combiner
sudo npm install -g tough-cookie
sudo npm install -g json-stringify-safe
sudo npm install -g qs
sudo npm install -g bl
sudo npm install -g hawk
sudo npm install -g aws-sign2
sudo npm install -g http-signature
sudo npm install -g mime-types
sudo npm install -g tunnel-agent
sudo npm install -g stringstream
sudo npm install -g forever-agent
sudo npm install -g combined-stream
sudo npm install -g mime-db
sudo npm install -g setimmediate
sudo npm install -g binary
sudo npm install -g pullstream
sudo npm install -g match-stream
sudo npm install -g inherits
sudo npm install -g mkdirp
sudo npm install -g rimraf
sudo npm install -g ionic-cordova-lib
sudo npm install -g htmlparser2
sudo npm install -g lodash
sudo npm install -g dom-serializer
sudo npm install -g css-select
